### ISSUE TITLE
Create Medication List Page

### ISSUE THREAD

**Issue by geoffreygraddy** [dose-amigos/dose-amigos-ionic#10]
This is an alphabetical list of medications with the ability to edit, delete, and add new medications.

**Comment by geoffreygraddy** [comment]
# Dose Page

- [ ] Create dose-medication .ts file
- [ ] Create add button for adding new medication

**Comment by jleopold28** [comment]
I already created a branch for this issue FYI. "Issue-10-Medication-List"
