### ISSUE TITLE
More Info links on the dose page should displays taken/snooze options

### ISSUE THREAD

**Issue by geoffreygraddy** [dose-amigos/dose-amigos-ionic#33]
Currently the more info link for a medication does nothing.  Make it so that it displays the  taken/snooze options as if the person slide the row to the left.

**Comment by mckoon** [comment]
Actually, in more info isn't going to show more information about the medicine, maybe it should just be an icon button indicating there are more actions.

**Comment by geoffreygraddy** [comment]
How about just changing the words "More Info" to "Actions"?

**Comment by geoffreygraddy** [comment]
Issue closed with the merge of FAB and checkboxes.
