### ISSUE TITLE
Create Dose Page

### ISSUE THREAD

**Issue by mckoon** [dose-amigos/dose-amigos-ionic#4]
Need to design the UI and page flow here.
There are a lot of actions that can be done.
May need to split into separate pages in the menu, have tabs in this page, or both.

Requirements:

Taking:
Need a way to take medication.
Need a way to see medication already taken.
Need a way to see upcoming.

Management:
Need a listing of all medicines being taken.
Need a warning if any known interactions.
Need a way to add new medications and set their schedule.
Need a way to edit existing schedules.
Need a way to delete a medication / schedule.
Enable/Disable reminder?

**Comment by geoffreygraddy** [comment]
Writing down what Jay said after class.  We need a .ts file for the medication object and a .ts file for the schedule object.

**Comment by geoffreygraddy** [comment]
- [ ] Create dose-medication

**Comment by geoffreygraddy** [comment]
I think two pages/tabs need to be created.  A Dose tab that list your medication where you can add/delete/edit and enable/disable reminders and a Dose Schedule tab that lists the past/present/future medications to be taken.

**Comment by geoffreygraddy** [comment]
# Dose Page

- [ ] Create dose-medication .ts file
