### ISSUE TITLE
Create Login Process

### ISSUE THREAD

**Issue by mckoon** [dose-amigos/dose-amigos-ionic#5]
Create a process/page for unauthenticated users to log-in.
As we are using Google for authentication, not sure what views we are responsible for, and what is provided by Google.

Is a Sign Up / Register page required, or just a "Sign In with Google" is good enough for both new and existing users?

Resources:
http://ionicframework.com/docs/v2/native/google-plus/
https://github.com/EddyVerbruggen/cordova-plugin-googleplus (note comment about npm out-of-date)

**Comment by mckoon** [comment]
https://github.com/EddyVerbruggen/cordova-plugin-googleplus

From looking into this a little more, it looks like the version available in npm is obsolete, using the deprecated google-plus endpoints for authorization. The current version on github uses Google Sign-In endpoints instead.

Setup:

```
ionic plugin add https://github.com/EddyVerbruggen/cordova-plugin-googleplus --save --variable REVERSED_CLIENT_ID=myreversedclientid
```

@jking31cs - read through the entire https://github.com/EddyVerbruggen/cordova-plugin-googleplus README.md and please provide any details that it references that we will need to talk to the backend on this ticket.

**Comment by mckoon** [comment]
Google Sign-In Docs:
https://developers.google.com/identity/

**Comment by mckoon** [comment]
NOTES: I ran
```
keytool -exportcert -list -v \
-alias androiddebugkey -keystore ~/.android/debug.keystore
```

With password `android` to print the SHA-1 needed for the Google SIgn-on android step.

**Comment by jking31cs** [comment]
http://blog.ionic.io/ionic-2-and-auth0/, thoughts?  I have a clientId and clientSecret if you need it.

**Comment by mckoon** [comment]
I'm exploring the auth0 method now, as seems better defined and simpler if it will work.
